name: CI

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        # All supported PHP versions https://www.php.net/supported-versions.php
        php: [ '7.4', '8.0' ]

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{matrix.php}}
        extensions: fileinfo, json, pdo, mbstring

    - name: Install
      run: |
        composer install

    - name: Create env file
      run: |
        touch .env
        echo FLICKR_API_KEY=${FLICKR_API_KEY} > .env
        echo FLICKR_API_SECRET=${FLICKR_API_SECRET} > .env
        echo FLICKR_ACCESS_TOKEN=${FLICKR_ACCESS_TOKEN} > .env
        echo FLICKR_ACCESS_SECRET=${FLICKR_ACCESS_SECRET} > .env
        cat .env
      env:
        FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
        FLICKR_API_SECRET: ${{ secrets.FLICKR_API_SECRET }}
        FLICKR_ACCESS_TOKEN: ${{ secrets.FLICKR_ACCESS_TOKEN }}
        FLICKR_ACCESS_SECRET: ${{ secrets.FLICKR_ACCESS_SECRET }}

    - name: Dump FLICKR_API_KEY
      env:
        FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
      run: echo "$FLICKR_API_KEY"

    - name: Test
      run: |
        composer test
